import { createElement } from '@lwc/engine-dom';
import Lwc_eventProgrammatic_c from 'c/lwc_eventProgrammatic_c';

describe('c-lwc-event-programmatic-c', () => {
    afterEach(() => {
        // The jsdom instance is shared across test cases in a single file so reset the DOM
        while (document.body.firstChild) {
            document.body.removeChild(document.body.firstChild);
        }
    });

    it('TODO: test case generated by CLI command, please fill in test logic', () => {
        // Arrange
        const element = createElement('c-lwc-event-programmatic-c', {
            is: Lwc_eventProgrammatic_c
        });

        // Act
        document.body.appendChild(element);

        // Assert
        // const div = element.shadowRoot.querySelector('div');
        expect(1).toBe(1);
    });
});